// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGAp4mPXzuN0jKZ2L--i1H4AxxdKFwkp8',
    appId: '1:436168134849:web:dd4a6926d78c25a1638440',
    messagingSenderId: '436168134849',
    projectId: 'auth-login-36f99',
    authDomain: 'auth-login-36f99.firebaseapp.com',
    storageBucket: 'auth-login-36f99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByPGKDgOV3eTwI9ugqhNv12PZQACNPPLo',
    appId: '1:436168134849:android:d1e14c3825c4f72e638440',
    messagingSenderId: '436168134849',
    projectId: 'auth-login-36f99',
    storageBucket: 'auth-login-36f99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYc91hKpkorh6svRoo1u1Xkl5YR_wMlic',
    appId: '1:436168134849:ios:f655dddc47e4a794638440',
    messagingSenderId: '436168134849',
    projectId: 'auth-login-36f99',
    storageBucket: 'auth-login-36f99.firebasestorage.app',
    iosBundleId: 'com.example.pageLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYc91hKpkorh6svRoo1u1Xkl5YR_wMlic',
    appId: '1:436168134849:ios:f655dddc47e4a794638440',
    messagingSenderId: '436168134849',
    projectId: 'auth-login-36f99',
    storageBucket: 'auth-login-36f99.firebasestorage.app',
    iosBundleId: 'com.example.pageLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGAp4mPXzuN0jKZ2L--i1H4AxxdKFwkp8',
    appId: '1:436168134849:web:1bbd9279a7d17130638440',
    messagingSenderId: '436168134849',
    projectId: 'auth-login-36f99',
    authDomain: 'auth-login-36f99.firebaseapp.com',
    storageBucket: 'auth-login-36f99.firebasestorage.app',
  );
}
